services:
  # nginx-proxy-manager:
  #   image: jc21/nginx-proxy-manager:latest
  #   container_name: nginx-proxy-manager
  #   restart: unless-stopped
  #   ports:
  #     # Public HTTP Port
  #     - 80:80
  #     # Public HTTPS Port
  #     - 443:443
  #     # Admin Web Port
  #     - 81:81

  #   environment:
  #     TZ: ${TIMEZONE}
  #     PUID: 1000
  #     PGID: 1000

  #   volumes:
  #     - /home/${USER}/docker/files/nginx/data:/data
  #     - /home/${USER}/docker/files/nginx/letsencrypt:/etc/letsencrypt

  caddy:
    image: viv32/caddy-porkbun:2.8.4
    container_name: caddy
    restart: unless-stopped
    ports:
      # Public HTTP Port
      - 80:80
      # Public HTTPS Port
      - 443:443
      # Admin Web Port
      - 81:81
    # networks:
    #   caddy_macvlan:
    #     ipv4_address: ${CADDY_NETWORK_IP}

    environment:
      TZ: ${TIMEZONE}
      PUID: 1000
      PGID: 1000

    volumes:
      - /home/${USER}/docker/files/caddy/data:/data
      - /home/${USER}/docker/files/caddy/config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile


# networks:
#   caddy_macvlan:
#     driver: macvlan
#     driver_opts:
#       parent: eth0
#     ipam:
#       driver: default
#       config:
#         - subnet: ${ROUTER_SUBNET}
#           gateway: ${ROUTER_IP}
#           ip_range: ${ROUTER_IP_RANGE}