services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    # network_mode: host
    ports:
      # Public HTTP Port
      - 80:80
      # Public HTTPS Port
      - 443:443
      # Admin Web Port
      - 81:81

    environment:
      PUID: 1000
      PGID: 1000

    volumes:
      - /home/${USER}/docker/files/nginx/data:/data
      - /home/${USER}/docker/files/nginx/letsencrypt:/etc/letsencrypt

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp # Only required if you are using Pi-hole as your DHCP server
      - 82:80
      - 444:443
    environment:
      TZ: "America/Chicago"
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
      PIHOLE_DNS_: 127.0.0.1#5335
      FTLCONF_LOCAL_IPV4: ${PIHOLE_FTLCONF_LOCAL_IPV4}
    volumes:
      - /home/${USER}/docker/files/pihole/etc-pihole:/etc/pihole
      - /home/${USER}/docker/files/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
      - /home/${USER}/docker/files/pihole/etc-lighttpd/conf-enabled/:/etc/lighttpd/conf-enabled/
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
    depends_on:
      - unbound

  unbound:
    container_name: unbound
    image: mvance/unbound-rpi:latest
    environment:
      TZ: "America/Chicago"
    ports:
      - 5335:53/tcp
      - 5335:53/udp
    volumes:
      - /home/${USER}/docker/files/unbound/config:/opt/unbound/etc/unbound/
      - /home/${USER}/docker/files/unbound/root.hints:/var/lib/unbound/root.hints
    restart: unless-stopped

  # https://docs.pi-hole.net/guides/vpn/wireguard/server/
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
      SERVERURL: piwireguard.getboolean.dev
      LOG_CONFS: true
    volumes:
      - /home/${USER}/docker/files/wireguard/etc-wireguard:/etc/wireguard/
      - /home/${USER}/docker/files/wireguard/config:/config
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
    ports:
      - 51820:51820/udp

      # Wireguard UI
      - 5000:5000
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    depends_on:
      - unbound
      - pihole

  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    cap_add:
      - NET_ADMIN
    network_mode: service:wireguard
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - /home/${USER}/docker/files/wireguard-ui/db:/app/db
      - /home/${USER}/docker/files/wireguard-ui/config:/config
    restart: unless-stopped

  duckdns:
    image: linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - SUBDOMAINS=getboolean
      - TOKEN=${DUCKDNS_TOKEN}
      - LOG_FILE=true
    volumes:
      - /home/${USER}/docker/files/duckdns/config:/config
    restart: unless-stopped
