services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      # Public HTTP Port
      - 80:80
      # Public HTTPS Port
      - 443:443
      # Admin Web Port
      - 81:81

    environment:
      TZ: ${TIMEZONE}
      PUID: 1000
      PGID: 1000

    volumes:
      - /home/${USER}/docker/files/nginx/data:/data
      - /home/${USER}/docker/files/nginx/letsencrypt:/etc/letsencrypt
